chore: format shellscripts with shfmt (#405)

diff --git a/config/.bin/git-clean-branch b/config/.bin/git-clean-branch
--- a/config/.bin/git-clean-branch
+++ b/config/.bin/git-clean-branch
@@ -6,11 +6,11 @@ set -eu
 
 clean_local() {
   local base=${1:-$(git default-branch)}
-  git branch --merged \
-    | grep -v ${base} \
-    | grep -v '*' \
-    | grep -v '^\s*$' \
-    | {
+  git branch --merged |
+    grep -v ${base} |
+    grep -v '*' |
+    grep -v '^\s*$' |
+    {
       local target=$(cat)
       if [ ${#target} -gt 0 ]; then
         git branch -d ${target}
@@ -23,11 +23,11 @@ clean_local() {
 clean_remote() {
   local remote=${1:-origin}
   local base=${2:-$(git default-branch)}
-  git branch --remotes --merged \
-    | grep ${remote}/ \
-    | grep -v ${base} \
-    | sed s~${remote}/~:~ \
-    | {
+  git branch --remotes --merged |
+    grep ${remote}/ |
+    grep -v ${base} |
+    sed s~${remote}/~:~ |
+    {
       local target=$(cat)
       if [ ${#target} -gt 0 ]; then
         git push origin $target
@@ -46,16 +46,16 @@ target="$1"
 shift
 
 case ${target} in
-  local|l)
-    clean_local
+local | l)
+  clean_local
   ;;
 
-  remote|r)
-    clean_remote
+remote | r)
+  clean_remote
   ;;
 
-  *)
-    printutil error "Invalid target"
-    exit 1
+*)
+  printutil error "Invalid target"
+  exit 1
   ;;
 esac
diff --git a/config/.bin/printutil b/config/.bin/printutil
--- a/config/.bin/printutil
+++ b/config/.bin/printutil
@@ -18,7 +18,7 @@ Usage:
 Commands:
     $(eval $0 header "header")
     $(eval $0 section "section")
-    $(eval $0 subsection  "subsection")
+    $(eval $0 subsection "subsection")
     $(eval $0 success "success")
     $(eval $0 error "error" 2>&1)
     $(eval $0 warning "warning")
@@ -89,38 +89,38 @@ main() {
   shift
 
   case ${subcommand} in
-    header)
-      print_header "$@"
-      ;;
+  header)
+    print_header "$@"
+    ;;
 
-    section)
-      print_section "$@"
-      ;;
+  section)
+    print_section "$@"
+    ;;
 
-    subsection)
-      print_subsection "$@"
-      ;;
+  subsection)
+    print_subsection "$@"
+    ;;
 
-    success)
-      print_success "$@"
-      ;;
+  success)
+    print_success "$@"
+    ;;
 
-    error)
-      print_error "$@"
-      ;;
+  error)
+    print_error "$@"
+    ;;
 
-    warning)
-      print_warning "$@"
-      ;;
+  warning)
+    print_warning "$@"
+    ;;
 
-    note)
-      print_note "$@"
-      ;;
+  note)
+    print_note "$@"
+    ;;
 
-    *)
-      eval $0 error "Invalid arguments"
-      exit 1
-      ;;
+  *)
+    eval $0 error "Invalid arguments"
+    exit 1
+    ;;
   esac
 }
 
@@ -130,15 +130,15 @@ if [ $# -lt 1 ]; then
 fi
 
 case ${1} in
-  --version|-v)
-    version
+--version | -v)
+  version
   ;;
 
-  --help|-h)
-    usage
+--help | -h)
+  usage
   ;;
 
-  *)
-    main $@
-    ;;
+*)
+  main $@
+  ;;
 esac
